version: '3'

services:
  microservicedemo:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  order:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  apigatewaynetcore:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  price:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  payment:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
